# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1280, 720)
        MainWindow.setMinimumSize(QtCore.QSize(1280, 720))
        MainWindow.setMaximumSize(QtCore.QSize(1280, 720))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(14)
        MainWindow.setFont(font)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("background-color: #fff;")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(12)
        self.centralwidget.setFont(font)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 1281, 691))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_left = QtWidgets.QVBoxLayout()
        self.verticalLayout_left.setObjectName("verticalLayout_left")
        self.groupBox_steuerung = QtWidgets.QGroupBox(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_steuerung.setFont(font)
        self.groupBox_steuerung.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_steuerung.setObjectName("groupBox_steuerung")
        self.groupBox_steuerung_slider = QtWidgets.QGroupBox(self.groupBox_steuerung)
        self.groupBox_steuerung_slider.setEnabled(False)
        self.groupBox_steuerung_slider.setGeometry(QtCore.QRect(10, 420, 400, 90))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(10)
        self.groupBox_steuerung_slider.setFont(font)
        self.groupBox_steuerung_slider.setStyleSheet("border-color: #000;\n"
"border-radius: 5px;\n"
"border-style: solid;\n"
"border-width: 2px;\n"
"")
        self.groupBox_steuerung_slider.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_steuerung_slider.setObjectName("groupBox_steuerung_slider")
        self.pushButton_steuerung_slider = QtWidgets.QPushButton(self.groupBox_steuerung_slider)
        self.pushButton_steuerung_slider.setEnabled(False)
        self.pushButton_steuerung_slider.setGeometry(QtCore.QRect(125, 30, 150, 30))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(18)
        self.pushButton_steuerung_slider.setFont(font)
        self.pushButton_steuerung_slider.setFlat(False)
        self.pushButton_steuerung_slider.setObjectName("pushButton_steuerung_slider")
        self.verticalLayout_left.addWidget(self.groupBox_steuerung)
        self.horizontalLayout.addLayout(self.verticalLayout_left)
        self.verticalLayout_center = QtWidgets.QVBoxLayout()
        self.verticalLayout_center.setObjectName("verticalLayout_center")
        self.groupBox_settings = QtWidgets.QGroupBox(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_settings.setFont(font)
        self.groupBox_settings.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_settings.setObjectName("groupBox_settings")
        self.groupBox_settings_slider = QtWidgets.QGroupBox(self.groupBox_settings)
        self.groupBox_settings_slider.setEnabled(False)
        self.groupBox_settings_slider.setGeometry(QtCore.QRect(10, 420, 400, 215))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(10)
        self.groupBox_settings_slider.setFont(font)
        self.groupBox_settings_slider.setStyleSheet("border-color: #000;\n"
"border-radius: 5px;\n"
"border-style: solid;\n"
"border-width: 2px;\n"
"")
        self.groupBox_settings_slider.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_settings_slider.setObjectName("groupBox_settings_slider")
        self.label_settings_slider_start = QtWidgets.QLabel(self.groupBox_settings_slider)
        self.label_settings_slider_start.setGeometry(QtCore.QRect(15, 15, 187, 30))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(14)
        self.label_settings_slider_start.setFont(font)
        self.label_settings_slider_start.setStyleSheet("border: none;\n"
"background-color: transparent;")
        self.label_settings_slider_start.setAlignment(QtCore.Qt.AlignCenter)
        self.label_settings_slider_start.setObjectName("label_settings_slider_start")
        self.comboBox_settings_slider_start = QtWidgets.QComboBox(self.groupBox_settings_slider)
        self.comboBox_settings_slider_start.setGeometry(QtCore.QRect(210, 15, 185, 30))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(14)
        self.comboBox_settings_slider_start.setFont(font)
        self.comboBox_settings_slider_start.setStyleSheet("border: none;\n"
"background-color: transparent;")
        self.comboBox_settings_slider_start.setEditable(False)
        self.comboBox_settings_slider_start.setObjectName("comboBox_settings_slider_start")
        self.comboBox_settings_slider_start.addItem("")
        self.comboBox_settings_slider_start.addItem("")
        self.comboBox_settings_slider_start.addItem("")
        self.label_settings_slider_richtung = QtWidgets.QLabel(self.groupBox_settings_slider)
        self.label_settings_slider_richtung.setGeometry(QtCore.QRect(15, 55, 187, 30))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(14)
        self.label_settings_slider_richtung.setFont(font)
        self.label_settings_slider_richtung.setStyleSheet("border: none;\n"
"background-color: transparent;")
        self.label_settings_slider_richtung.setAlignment(QtCore.Qt.AlignCenter)
        self.label_settings_slider_richtung.setObjectName("label_settings_slider_richtung")
        self.comboBox_settings_slider_richtung = QtWidgets.QComboBox(self.groupBox_settings_slider)
        self.comboBox_settings_slider_richtung.setGeometry(QtCore.QRect(210, 55, 185, 30))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(14)
        self.comboBox_settings_slider_richtung.setFont(font)
        self.comboBox_settings_slider_richtung.setStyleSheet("border: none;\n"
"background-color: transparent;")
        self.comboBox_settings_slider_richtung.setEditable(False)
        self.comboBox_settings_slider_richtung.setObjectName("comboBox_settings_slider_richtung")
        self.comboBox_settings_slider_richtung.addItem("")
        self.comboBox_settings_slider_richtung.addItem("")
        self.label_settings_slider_steps = QtWidgets.QLabel(self.groupBox_settings_slider)
        self.label_settings_slider_steps.setGeometry(QtCore.QRect(15, 95, 187, 30))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(14)
        self.label_settings_slider_steps.setFont(font)
        self.label_settings_slider_steps.setStyleSheet("border: none;\n"
"background-color: transparent;")
        self.label_settings_slider_steps.setAlignment(QtCore.Qt.AlignCenter)
        self.label_settings_slider_steps.setObjectName("label_settings_slider_steps")
        self.lineEdit_settings_slider_steps = QtWidgets.QLineEdit(self.groupBox_settings_slider)
        self.lineEdit_settings_slider_steps.setGeometry(QtCore.QRect(210, 95, 185, 30))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(18)
        self.lineEdit_settings_slider_steps.setFont(font)
        self.lineEdit_settings_slider_steps.setStyleSheet("background-color: transparent;")
        self.lineEdit_settings_slider_steps.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_settings_slider_steps.setObjectName("lineEdit_settings_slider_steps")
        self.label_settings_slider_frequenz = QtWidgets.QLabel(self.groupBox_settings_slider)
        self.label_settings_slider_frequenz.setGeometry(QtCore.QRect(15, 135, 187, 30))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(14)
        self.label_settings_slider_frequenz.setFont(font)
        self.label_settings_slider_frequenz.setStyleSheet("border: none;\n"
"background-color: transparent;")
        self.label_settings_slider_frequenz.setAlignment(QtCore.Qt.AlignCenter)
        self.label_settings_slider_frequenz.setObjectName("label_settings_slider_frequenz")
        self.lineEdit_settings_slider_frequenz = QtWidgets.QLineEdit(self.groupBox_settings_slider)
        self.lineEdit_settings_slider_frequenz.setGeometry(QtCore.QRect(210, 135, 185, 30))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(18)
        self.lineEdit_settings_slider_frequenz.setFont(font)
        self.lineEdit_settings_slider_frequenz.setStyleSheet("background-color: transparent;")
        self.lineEdit_settings_slider_frequenz.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_settings_slider_frequenz.setObjectName("lineEdit_settings_slider_frequenz")
        self.pushButton_settings_slider = QtWidgets.QPushButton(self.groupBox_settings_slider)
        self.pushButton_settings_slider.setEnabled(False)
        self.pushButton_settings_slider.setGeometry(QtCore.QRect(125, 175, 150, 30))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(18)
        self.pushButton_settings_slider.setFont(font)
        self.pushButton_settings_slider.setFlat(False)
        self.pushButton_settings_slider.setObjectName("pushButton_settings_slider")
        self.verticalLayout_center.addWidget(self.groupBox_settings)
        self.horizontalLayout.addLayout(self.verticalLayout_center)
        self.verticalLayout_right = QtWidgets.QVBoxLayout()
        self.verticalLayout_right.setObjectName("verticalLayout_right")
        self.groupBox_info = QtWidgets.QGroupBox(self.horizontalLayoutWidget)
        self.groupBox_info.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_info.setFont(font)
        self.groupBox_info.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_info.setFlat(False)
        self.groupBox_info.setCheckable(False)
        self.groupBox_info.setObjectName("groupBox_info")
        self.groupBox_info_server = QtWidgets.QGroupBox(self.groupBox_info)
        self.groupBox_info_server.setGeometry(QtCore.QRect(10, 30, 400, 55))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_info_server.sizePolicy().hasHeightForWidth())
        self.groupBox_info_server.setSizePolicy(sizePolicy)
        self.groupBox_info_server.setMinimumSize(QtCore.QSize(400, 55))
        self.groupBox_info_server.setMaximumSize(QtCore.QSize(400, 55))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(10)
        self.groupBox_info_server.setFont(font)
        self.groupBox_info_server.setStyleSheet("border-color: #000;\n"
"border-radius: 5px;\n"
"border-style: solid;\n"
"border-width: 2px;\n"
"")
        self.groupBox_info_server.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_info_server.setObjectName("groupBox_info_server")
        self.label_info_server = QtWidgets.QLabel(self.groupBox_info_server)
        self.label_info_server.setGeometry(QtCore.QRect(15, 15, 187, 30))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(14)
        self.label_info_server.setFont(font)
        self.label_info_server.setStyleSheet("border: none;")
        self.label_info_server.setAlignment(QtCore.Qt.AlignCenter)
        self.label_info_server.setObjectName("label_info_server")
        self.label_info_server_ip = QtWidgets.QLabel(self.groupBox_info_server)
        self.label_info_server_ip.setGeometry(QtCore.QRect(210, 15, 187, 30))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(14)
        self.label_info_server_ip.setFont(font)
        self.label_info_server_ip.setStyleSheet("color: #DB2828;\n"
"border: none;")
        self.label_info_server_ip.setAlignment(QtCore.Qt.AlignCenter)
        self.label_info_server_ip.setObjectName("label_info_server_ip")
        self.groupBox_info_kamera = QtWidgets.QGroupBox(self.groupBox_info)
        self.groupBox_info_kamera.setGeometry(QtCore.QRect(10, 100, 400, 300))
        self.groupBox_info_kamera.setMinimumSize(QtCore.QSize(400, 300))
        self.groupBox_info_kamera.setMaximumSize(QtCore.QSize(400, 300))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(10)
        self.groupBox_info_kamera.setFont(font)
        self.groupBox_info_kamera.setStyleSheet("border-color: #000;\n"
"border-radius: 5px;\n"
"border-style: solid;\n"
"border-width: 2px;")
        self.groupBox_info_kamera.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_info_kamera.setObjectName("groupBox_info_kamera")
        self.label_info_camera_name = QtWidgets.QLabel(self.groupBox_info_kamera)
        self.label_info_camera_name.setGeometry(QtCore.QRect(15, 15, 187, 30))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(14)
        self.label_info_camera_name.setFont(font)
        self.label_info_camera_name.setStyleSheet("border: none;\n"
"background-color: transparent;")
        self.label_info_camera_name.setAlignment(QtCore.Qt.AlignCenter)
        self.label_info_camera_name.setObjectName("label_info_camera_name")
        self.input_info_camera_name = QtWidgets.QLabel(self.groupBox_info_kamera)
        self.input_info_camera_name.setGeometry(QtCore.QRect(210, 15, 186, 30))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(14)
        self.input_info_camera_name.setFont(font)
        self.input_info_camera_name.setStyleSheet("border: none;\n"
"color: #DB2828;")
        self.input_info_camera_name.setAlignment(QtCore.Qt.AlignCenter)
        self.input_info_camera_name.setObjectName("input_info_camera_name")
        self.label_info_camera_akku = QtWidgets.QLabel(self.groupBox_info_kamera)
        self.label_info_camera_akku.setEnabled(False)
        self.label_info_camera_akku.setGeometry(QtCore.QRect(15, 55, 187, 30))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(14)
        self.label_info_camera_akku.setFont(font)
        self.label_info_camera_akku.setStyleSheet("border: none;\n"
"background-color: transparent;")
        self.label_info_camera_akku.setAlignment(QtCore.Qt.AlignCenter)
        self.label_info_camera_akku.setObjectName("label_info_camera_akku")
        self.label_info_camera_blende = QtWidgets.QLabel(self.groupBox_info_kamera)
        self.label_info_camera_blende.setEnabled(False)
        self.label_info_camera_blende.setGeometry(QtCore.QRect(15, 95, 187, 30))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(14)
        self.label_info_camera_blende.setFont(font)
        self.label_info_camera_blende.setStyleSheet("border: none;\n"
"background-color: transparent;")
        self.label_info_camera_blende.setAlignment(QtCore.Qt.AlignCenter)
        self.label_info_camera_blende.setObjectName("label_info_camera_blende")
        self.label_info_camera_shutter = QtWidgets.QLabel(self.groupBox_info_kamera)
        self.label_info_camera_shutter.setEnabled(False)
        self.label_info_camera_shutter.setGeometry(QtCore.QRect(15, 135, 187, 30))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(14)
        self.label_info_camera_shutter.setFont(font)
        self.label_info_camera_shutter.setStyleSheet("border: none;\n"
"background-color: transparent;")
        self.label_info_camera_shutter.setAlignment(QtCore.Qt.AlignCenter)
        self.label_info_camera_shutter.setObjectName("label_info_camera_shutter")
        self.label_info_camera_iso = QtWidgets.QLabel(self.groupBox_info_kamera)
        self.label_info_camera_iso.setEnabled(False)
        self.label_info_camera_iso.setGeometry(QtCore.QRect(15, 175, 187, 30))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(14)
        self.label_info_camera_iso.setFont(font)
        self.label_info_camera_iso.setStyleSheet("border: none;\n"
"background-color: transparent;")
        self.label_info_camera_iso.setAlignment(QtCore.Qt.AlignCenter)
        self.label_info_camera_iso.setObjectName("label_info_camera_iso")
        self.label_info_camera_fokus = QtWidgets.QLabel(self.groupBox_info_kamera)
        self.label_info_camera_fokus.setEnabled(False)
        self.label_info_camera_fokus.setGeometry(QtCore.QRect(15, 215, 187, 30))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(14)
        self.label_info_camera_fokus.setFont(font)
        self.label_info_camera_fokus.setStyleSheet("border: none;\n"
"background-color: transparent;")
        self.label_info_camera_fokus.setAlignment(QtCore.Qt.AlignCenter)
        self.label_info_camera_fokus.setObjectName("label_info_camera_fokus")
        self.label_info_camera_format = QtWidgets.QLabel(self.groupBox_info_kamera)
        self.label_info_camera_format.setEnabled(False)
        self.label_info_camera_format.setGeometry(QtCore.QRect(15, 255, 187, 30))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(14)
        self.label_info_camera_format.setFont(font)
        self.label_info_camera_format.setStyleSheet("border: none;\n"
"background-color: transparent;")
        self.label_info_camera_format.setAlignment(QtCore.Qt.AlignCenter)
        self.label_info_camera_format.setObjectName("label_info_camera_format")
        self.input_info_camera_akku = QtWidgets.QLabel(self.groupBox_info_kamera)
        self.input_info_camera_akku.setEnabled(False)
        self.input_info_camera_akku.setGeometry(QtCore.QRect(210, 55, 186, 30))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(14)
        self.input_info_camera_akku.setFont(font)
        self.input_info_camera_akku.setStyleSheet("border: none;")
        self.input_info_camera_akku.setText("")
        self.input_info_camera_akku.setAlignment(QtCore.Qt.AlignCenter)
        self.input_info_camera_akku.setObjectName("input_info_camera_akku")
        self.input_info_camera_blende = QtWidgets.QLabel(self.groupBox_info_kamera)
        self.input_info_camera_blende.setEnabled(True)
        self.input_info_camera_blende.setGeometry(QtCore.QRect(210, 95, 186, 30))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(14)
        self.input_info_camera_blende.setFont(font)
        self.input_info_camera_blende.setStyleSheet("border: none;")
        self.input_info_camera_blende.setText("")
        self.input_info_camera_blende.setAlignment(QtCore.Qt.AlignCenter)
        self.input_info_camera_blende.setObjectName("input_info_camera_blende")
        self.input_info_camera_shutter = QtWidgets.QLabel(self.groupBox_info_kamera)
        self.input_info_camera_shutter.setEnabled(False)
        self.input_info_camera_shutter.setGeometry(QtCore.QRect(210, 135, 186, 30))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(14)
        self.input_info_camera_shutter.setFont(font)
        self.input_info_camera_shutter.setStyleSheet("border: none;")
        self.input_info_camera_shutter.setText("")
        self.input_info_camera_shutter.setAlignment(QtCore.Qt.AlignCenter)
        self.input_info_camera_shutter.setObjectName("input_info_camera_shutter")
        self.input_info_camera_iso = QtWidgets.QLabel(self.groupBox_info_kamera)
        self.input_info_camera_iso.setEnabled(False)
        self.input_info_camera_iso.setGeometry(QtCore.QRect(210, 175, 186, 30))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(14)
        self.input_info_camera_iso.setFont(font)
        self.input_info_camera_iso.setStyleSheet("border: none;")
        self.input_info_camera_iso.setText("")
        self.input_info_camera_iso.setAlignment(QtCore.Qt.AlignCenter)
        self.input_info_camera_iso.setObjectName("input_info_camera_iso")
        self.input_info_camera_fokus = QtWidgets.QLabel(self.groupBox_info_kamera)
        self.input_info_camera_fokus.setEnabled(False)
        self.input_info_camera_fokus.setGeometry(QtCore.QRect(210, 215, 186, 30))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(14)
        self.input_info_camera_fokus.setFont(font)
        self.input_info_camera_fokus.setStyleSheet("border: none;")
        self.input_info_camera_fokus.setText("")
        self.input_info_camera_fokus.setAlignment(QtCore.Qt.AlignCenter)
        self.input_info_camera_fokus.setObjectName("input_info_camera_fokus")
        self.input_info_camera_format = QtWidgets.QLabel(self.groupBox_info_kamera)
        self.input_info_camera_format.setEnabled(False)
        self.input_info_camera_format.setGeometry(QtCore.QRect(210, 255, 186, 30))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(14)
        self.input_info_camera_format.setFont(font)
        self.input_info_camera_format.setStyleSheet("border: none;")
        self.input_info_camera_format.setText("")
        self.input_info_camera_format.setAlignment(QtCore.Qt.AlignCenter)
        self.input_info_camera_format.setObjectName("input_info_camera_format")
        self.groupBox_info_slider = QtWidgets.QGroupBox(self.groupBox_info)
        self.groupBox_info_slider.setEnabled(False)
        self.groupBox_info_slider.setGeometry(QtCore.QRect(10, 420, 400, 250))
        self.groupBox_info_slider.setMinimumSize(QtCore.QSize(400, 250))
        self.groupBox_info_slider.setMaximumSize(QtCore.QSize(400, 250))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(10)
        self.groupBox_info_slider.setFont(font)
        self.groupBox_info_slider.setStyleSheet("border-color: #000;\n"
"border-radius: 5px;\n"
"border-style: solid;\n"
"border-width: 2px;")
        self.groupBox_info_slider.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_info_slider.setObjectName("groupBox_info_slider")
        self.label_info_slider_links = QtWidgets.QLabel(self.groupBox_info_slider)
        self.label_info_slider_links.setEnabled(False)
        self.label_info_slider_links.setGeometry(QtCore.QRect(15, 15, 187, 30))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(14)
        self.label_info_slider_links.setFont(font)
        self.label_info_slider_links.setStyleSheet("border: none;\n"
"background-color: transparent;")
        self.label_info_slider_links.setAlignment(QtCore.Qt.AlignCenter)
        self.label_info_slider_links.setObjectName("label_info_slider_links")
        self.label_info_slider_rechts = QtWidgets.QLabel(self.groupBox_info_slider)
        self.label_info_slider_rechts.setEnabled(False)
        self.label_info_slider_rechts.setGeometry(QtCore.QRect(15, 55, 187, 30))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(14)
        self.label_info_slider_rechts.setFont(font)
        self.label_info_slider_rechts.setStyleSheet("border: none;\n"
"background-color: transparent;")
        self.label_info_slider_rechts.setAlignment(QtCore.Qt.AlignCenter)
        self.label_info_slider_rechts.setObjectName("label_info_slider_rechts")
        self.input_info_slider_links = QtWidgets.QLabel(self.groupBox_info_slider)
        self.input_info_slider_links.setEnabled(False)
        self.input_info_slider_links.setGeometry(QtCore.QRect(210, 15, 186, 30))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(14)
        self.input_info_slider_links.setFont(font)
        self.input_info_slider_links.setStyleSheet("border: none;")
        self.input_info_slider_links.setText("")
        self.input_info_slider_links.setAlignment(QtCore.Qt.AlignCenter)
        self.input_info_slider_links.setObjectName("input_info_slider_links")
        self.input_info_slider_rechts = QtWidgets.QLabel(self.groupBox_info_slider)
        self.input_info_slider_rechts.setEnabled(False)
        self.input_info_slider_rechts.setGeometry(QtCore.QRect(210, 55, 186, 30))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(14)
        self.input_info_slider_rechts.setFont(font)
        self.input_info_slider_rechts.setStyleSheet("border: none;")
        self.input_info_slider_rechts.setText("")
        self.input_info_slider_rechts.setAlignment(QtCore.Qt.AlignCenter)
        self.input_info_slider_rechts.setObjectName("input_info_slider_rechts")
        self.label_info_slider_frequenz = QtWidgets.QLabel(self.groupBox_info_slider)
        self.label_info_slider_frequenz.setEnabled(False)
        self.label_info_slider_frequenz.setGeometry(QtCore.QRect(15, 135, 187, 30))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(14)
        self.label_info_slider_frequenz.setFont(font)
        self.label_info_slider_frequenz.setStyleSheet("border: none;\n"
"background-color: transparent;")
        self.label_info_slider_frequenz.setAlignment(QtCore.Qt.AlignCenter)
        self.label_info_slider_frequenz.setObjectName("label_info_slider_frequenz")
        self.input_info_slider_status = QtWidgets.QLabel(self.groupBox_info_slider)
        self.input_info_slider_status.setEnabled(False)
        self.input_info_slider_status.setGeometry(QtCore.QRect(210, 95, 186, 30))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(14)
        self.input_info_slider_status.setFont(font)
        self.input_info_slider_status.setStyleSheet("border: none;")
        self.input_info_slider_status.setText("")
        self.input_info_slider_status.setAlignment(QtCore.Qt.AlignCenter)
        self.input_info_slider_status.setObjectName("input_info_slider_status")
        self.label_info_slider_status = QtWidgets.QLabel(self.groupBox_info_slider)
        self.label_info_slider_status.setEnabled(False)
        self.label_info_slider_status.setGeometry(QtCore.QRect(15, 95, 187, 30))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(14)
        self.label_info_slider_status.setFont(font)
        self.label_info_slider_status.setStyleSheet("border: none;\n"
"background-color: transparent;")
        self.label_info_slider_status.setAlignment(QtCore.Qt.AlignCenter)
        self.label_info_slider_status.setObjectName("label_info_slider_status")
        self.input_info_slider_frequenz = QtWidgets.QLabel(self.groupBox_info_slider)
        self.input_info_slider_frequenz.setEnabled(False)
        self.input_info_slider_frequenz.setGeometry(QtCore.QRect(210, 135, 186, 30))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(14)
        self.input_info_slider_frequenz.setFont(font)
        self.input_info_slider_frequenz.setStyleSheet("border: none;")
        self.input_info_slider_frequenz.setText("")
        self.input_info_slider_frequenz.setAlignment(QtCore.Qt.AlignCenter)
        self.input_info_slider_frequenz.setObjectName("input_info_slider_frequenz")
        self.label_info_slider_richtung = QtWidgets.QLabel(self.groupBox_info_slider)
        self.label_info_slider_richtung.setEnabled(False)
        self.label_info_slider_richtung.setGeometry(QtCore.QRect(15, 175, 187, 30))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(14)
        self.label_info_slider_richtung.setFont(font)
        self.label_info_slider_richtung.setStyleSheet("border: none;\n"
"background-color: transparent;")
        self.label_info_slider_richtung.setAlignment(QtCore.Qt.AlignCenter)
        self.label_info_slider_richtung.setObjectName("label_info_slider_richtung")
        self.input_info_slider_richtung = QtWidgets.QLabel(self.groupBox_info_slider)
        self.input_info_slider_richtung.setEnabled(False)
        self.input_info_slider_richtung.setGeometry(QtCore.QRect(210, 175, 186, 30))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(14)
        self.input_info_slider_richtung.setFont(font)
        self.input_info_slider_richtung.setStyleSheet("border: none;")
        self.input_info_slider_richtung.setText("")
        self.input_info_slider_richtung.setAlignment(QtCore.Qt.AlignCenter)
        self.input_info_slider_richtung.setObjectName("input_info_slider_richtung")
        self.label_info_slider_steps = QtWidgets.QLabel(self.groupBox_info_slider)
        self.label_info_slider_steps.setGeometry(QtCore.QRect(15, 210, 187, 30))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(14)
        self.label_info_slider_steps.setFont(font)
        self.label_info_slider_steps.setStyleSheet("border: none;\n"
"background-color: transparent;")
        self.label_info_slider_steps.setAlignment(QtCore.Qt.AlignCenter)
        self.label_info_slider_steps.setObjectName("label_info_slider_steps")
        self.input_info_slider_steps = QtWidgets.QLabel(self.groupBox_info_slider)
        self.input_info_slider_steps.setEnabled(False)
        self.input_info_slider_steps.setGeometry(QtCore.QRect(210, 210, 186, 30))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(14)
        self.input_info_slider_steps.setFont(font)
        self.input_info_slider_steps.setStyleSheet("border: none;")
        self.input_info_slider_steps.setText("")
        self.input_info_slider_steps.setAlignment(QtCore.Qt.AlignCenter)
        self.input_info_slider_steps.setObjectName("input_info_slider_steps")
        self.verticalLayout_right.addWidget(self.groupBox_info)
        self.horizontalLayout.addLayout(self.verticalLayout_right)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1280, 22))
        self.menubar.setMinimumSize(QtCore.QSize(1280, 22))
        self.menubar.setMaximumSize(QtCore.QSize(1280, 22))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(10)
        self.menubar.setFont(font)
        self.menubar.setObjectName("menubar")
        self.menuServer = QtWidgets.QMenu(self.menubar)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        self.menuServer.setFont(font)
        self.menuServer.setObjectName("menuServer")
        self.menuProgramm = QtWidgets.QMenu(self.menubar)
        self.menuProgramm.setObjectName("menuProgramm")
        MainWindow.setMenuBar(self.menubar)
        self.actionConnect = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        self.actionConnect.setFont(font)
        self.actionConnect.setObjectName("actionConnect")
        self.actionDisconnect = QtWidgets.QAction(MainWindow)
        self.actionDisconnect.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        self.actionDisconnect.setFont(font)
        self.actionDisconnect.setObjectName("actionDisconnect")
        self.actionConnectCamera = QtWidgets.QAction(MainWindow)
        self.actionConnectCamera.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        self.actionConnectCamera.setFont(font)
        self.actionConnectCamera.setObjectName("actionConnectCamera")
        self.actionExportieren = QtWidgets.QAction(MainWindow)
        self.actionExportieren.setObjectName("actionExportieren")
        self.actionImportieren = QtWidgets.QAction(MainWindow)
        self.actionImportieren.setObjectName("actionImportieren")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionClose = QtWidgets.QAction(MainWindow)
        self.actionClose.setObjectName("actionClose")
        self.actionDisconnectCamera = QtWidgets.QAction(MainWindow)
        self.actionDisconnectCamera.setEnabled(False)
        self.actionDisconnectCamera.setObjectName("actionDisconnectCamera")
        self.actionConnectMotor = QtWidgets.QAction(MainWindow)
        self.actionConnectMotor.setEnabled(False)
        self.actionConnectMotor.setObjectName("actionConnectMotor")
        self.actionDisconnectMotor = QtWidgets.QAction(MainWindow)
        self.actionDisconnectMotor.setEnabled(False)
        self.actionDisconnectMotor.setObjectName("actionDisconnectMotor")
        self.menuServer.addAction(self.actionConnect)
        self.menuServer.addAction(self.actionDisconnect)
        self.menuServer.addSeparator()
        self.menuServer.addAction(self.actionConnectCamera)
        self.menuServer.addAction(self.actionDisconnectCamera)
        self.menuServer.addSeparator()
        self.menuServer.addAction(self.actionConnectMotor)
        self.menuServer.addAction(self.actionDisconnectMotor)
        self.menuProgramm.addAction(self.actionAbout)
        self.menuProgramm.addAction(self.actionClose)
        self.menubar.addAction(self.menuProgramm.menuAction())
        self.menubar.addAction(self.menuServer.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Camera Slider"))
        self.groupBox_steuerung.setTitle(_translate("MainWindow", "Einstellungen"))
        self.groupBox_steuerung_slider.setTitle(_translate("MainWindow", "Slider"))
        self.pushButton_steuerung_slider.setText(_translate("MainWindow", "Starten"))
        self.groupBox_settings.setTitle(_translate("MainWindow", "Einstellungen"))
        self.groupBox_settings_slider.setTitle(_translate("MainWindow", "Slider"))
        self.label_settings_slider_start.setText(_translate("MainWindow", "Startpunkt:"))
        self.comboBox_settings_slider_start.setItemText(0, _translate("MainWindow", "Links"))
        self.comboBox_settings_slider_start.setItemText(1, _translate("MainWindow", "Mitte"))
        self.comboBox_settings_slider_start.setItemText(2, _translate("MainWindow", "Rechts"))
        self.label_settings_slider_richtung.setText(_translate("MainWindow", "Richtung:"))
        self.comboBox_settings_slider_richtung.setItemText(0, _translate("MainWindow", "Rechts"))
        self.comboBox_settings_slider_richtung.setItemText(1, _translate("MainWindow", "Links"))
        self.label_settings_slider_steps.setText(_translate("MainWindow", "Schritte:"))
        self.lineEdit_settings_slider_steps.setPlaceholderText(_translate("MainWindow", "Schrittanzahl"))
        self.label_settings_slider_frequenz.setText(_translate("MainWindow", "Frequenz:"))
        self.lineEdit_settings_slider_frequenz.setPlaceholderText(_translate("MainWindow", "Schritte/Sekunde"))
        self.pushButton_settings_slider.setText(_translate("MainWindow", "Einstellen"))
        self.groupBox_info.setTitle(_translate("MainWindow", "Informationen"))
        self.groupBox_info_server.setTitle(_translate("MainWindow", "Server"))
        self.label_info_server.setText(_translate("MainWindow", "Verbunden mit:"))
        self.label_info_server_ip.setText(_translate("MainWindow", "Nicht verbunden"))
        self.groupBox_info_kamera.setTitle(_translate("MainWindow", "Kamera"))
        self.label_info_camera_name.setText(_translate("MainWindow", "Verbunden mit:"))
        self.input_info_camera_name.setText(_translate("MainWindow", "Nicht verbunden"))
        self.label_info_camera_akku.setText(_translate("MainWindow", "Akku:"))
        self.label_info_camera_blende.setText(_translate("MainWindow", "Blende:"))
        self.label_info_camera_shutter.setText(_translate("MainWindow", "Verschlusszeit:"))
        self.label_info_camera_iso.setText(_translate("MainWindow", "ISO:"))
        self.label_info_camera_fokus.setText(_translate("MainWindow", "Fokus:"))
        self.label_info_camera_format.setText(_translate("MainWindow", "Bildformat:"))
        self.groupBox_info_slider.setTitle(_translate("MainWindow", "Slider"))
        self.label_info_slider_links.setText(_translate("MainWindow", "Abstand Links:"))
        self.label_info_slider_rechts.setText(_translate("MainWindow", "Abstand Rechts:"))
        self.label_info_slider_frequenz.setText(_translate("MainWindow", "Frequenz:"))
        self.label_info_slider_status.setText(_translate("MainWindow", "Status:"))
        self.label_info_slider_richtung.setText(_translate("MainWindow", "Richtung:"))
        self.label_info_slider_steps.setText(_translate("MainWindow", "Schritte:"))
        self.menuServer.setTitle(_translate("MainWindow", "Server"))
        self.menuProgramm.setTitle(_translate("MainWindow", "Programm"))
        self.actionConnect.setText(_translate("MainWindow", "Verbinden"))
        self.actionDisconnect.setText(_translate("MainWindow", "Verbindung trennen"))
        self.actionConnectCamera.setText(_translate("MainWindow", "Kamera verbinden"))
        self.actionExportieren.setText(_translate("MainWindow", "Exportieren"))
        self.actionImportieren.setText(_translate("MainWindow", "Importieren"))
        self.actionAbout.setText(_translate("MainWindow", "Über"))
        self.actionAbout.setShortcut(_translate("MainWindow", "Ctrl+A"))
        self.actionClose.setText(_translate("MainWindow", "Beenden"))
        self.actionClose.setShortcut(_translate("MainWindow", "Ctrl+X"))
        self.actionDisconnectCamera.setText(_translate("MainWindow", "Kamera Verbindung trennen"))
        self.actionConnectMotor.setText(_translate("MainWindow", "Motor verbinden"))
        self.actionDisconnectMotor.setText(_translate("MainWindow", "Motor Verbindung trennen"))
