# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1280, 720)
        MainWindow.setMinimumSize(QtCore.QSize(1280, 720))
        MainWindow.setMaximumSize(QtCore.QSize(1280, 720))
        MainWindow.setStyleSheet("QMainWindow, QMenuBar, QMenu {    \n"
"    background-color: #c2c2c2;\n"
"}\n"
"\n"
"QMenu::item:enabled:selected {\n"
"    background-color: #f5f5f5;\n"
"    color: #000;\n"
"}\n"
"\n"
"QMenu::item:enabled {\n"
"    color: #000;\n"
"}\n"
"\n"
"QMenu::item:disabled {\n"
"    color: gray;\n"
"}\n"
"\n"
"QGroupBox {\n"
"    background-color: transparent;\n"
"    border: 2px solid #000;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QLabel {\n"
"    background-color: transparent;\n"
"    border: none;\n"
"    color: #000;\n"
"}\n"
"\n"
"QLabel:disabled {\n"
"    background-color: transparent;\n"
"    border: none;\n"
"    color: gray;\n"
"}\n"
"\n"
"QLabel:enabled {\n"
"    background-color: transparent;\n"
"    border: none;\n"
"    color: #000;\n"
"}\n"
"\n"
"QLabel#serverip, QLabel#cameraname {\n"
"    background-color: transparent;\n"
"    border: none;\n"
"    color: #DB2828;\n"
"}\n"
"\n"
"QLabel#serverip[connected=\"false\"], QLabel#cameraname[connected=\"false\"] {\n"
"    color: #DB2828;\n"
"}\n"
"\n"
"QLabel#serverip[connected=\"true\"], QLabel#cameraname[connected=\"true\"] {\n"
"    color: #00c853;\n"
"}\n"
"\n"
"Line {\n"
"    background-color: black;\n"
"}\n"
"\n"
"Line:disabled, Line:enabled {\n"
"    background-color: black;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 1281, 691))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_left = QtWidgets.QVBoxLayout()
        self.verticalLayout_left.setObjectName("verticalLayout_left")
        self.groupBox_info = QtWidgets.QGroupBox(self.horizontalLayoutWidget)
        self.groupBox_info.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_info.setFont(font)
        self.groupBox_info.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_info.setFlat(False)
        self.groupBox_info.setCheckable(False)
        self.groupBox_info.setObjectName("groupBox_info")
        self.groupBox_info_kamera = QtWidgets.QGroupBox(self.groupBox_info)
        self.groupBox_info_kamera.setEnabled(False)
        self.groupBox_info_kamera.setGeometry(QtCore.QRect(10, 30, 400, 300))
        self.groupBox_info_kamera.setMinimumSize(QtCore.QSize(400, 300))
        self.groupBox_info_kamera.setMaximumSize(QtCore.QSize(400, 300))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(10)
        self.groupBox_info_kamera.setFont(font)
        self.groupBox_info_kamera.setStyleSheet("")
        self.groupBox_info_kamera.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_info_kamera.setObjectName("groupBox_info_kamera")
        self.label_info_camera_name = QtWidgets.QLabel(self.groupBox_info_kamera)
        self.label_info_camera_name.setEnabled(False)
        self.label_info_camera_name.setGeometry(QtCore.QRect(15, 15, 187, 30))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(14)
        self.label_info_camera_name.setFont(font)
        self.label_info_camera_name.setStyleSheet("")
        self.label_info_camera_name.setAlignment(QtCore.Qt.AlignCenter)
        self.label_info_camera_name.setObjectName("label_info_camera_name")
        self.input_info_camera_name = QtWidgets.QLabel(self.groupBox_info_kamera)
        self.input_info_camera_name.setEnabled(False)
        self.input_info_camera_name.setGeometry(QtCore.QRect(210, 15, 186, 30))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(14)
        self.input_info_camera_name.setFont(font)
        self.input_info_camera_name.setStyleSheet("")
        self.input_info_camera_name.setAlignment(QtCore.Qt.AlignCenter)
        self.input_info_camera_name.setObjectName("input_info_camera_name")
        self.label_info_camera_akku = QtWidgets.QLabel(self.groupBox_info_kamera)
        self.label_info_camera_akku.setEnabled(False)
        self.label_info_camera_akku.setGeometry(QtCore.QRect(15, 55, 187, 30))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(14)
        self.label_info_camera_akku.setFont(font)
        self.label_info_camera_akku.setStyleSheet("")
        self.label_info_camera_akku.setAlignment(QtCore.Qt.AlignCenter)
        self.label_info_camera_akku.setObjectName("label_info_camera_akku")
        self.label_info_camera_blende = QtWidgets.QLabel(self.groupBox_info_kamera)
        self.label_info_camera_blende.setEnabled(False)
        self.label_info_camera_blende.setGeometry(QtCore.QRect(15, 95, 187, 30))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(14)
        self.label_info_camera_blende.setFont(font)
        self.label_info_camera_blende.setStyleSheet("border: none;\n"
"background-color: transparent;")
        self.label_info_camera_blende.setAlignment(QtCore.Qt.AlignCenter)
        self.label_info_camera_blende.setObjectName("label_info_camera_blende")
        self.label_info_camera_shutter = QtWidgets.QLabel(self.groupBox_info_kamera)
        self.label_info_camera_shutter.setEnabled(False)
        self.label_info_camera_shutter.setGeometry(QtCore.QRect(15, 135, 187, 30))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(14)
        self.label_info_camera_shutter.setFont(font)
        self.label_info_camera_shutter.setStyleSheet("border: none;\n"
"background-color: transparent;")
        self.label_info_camera_shutter.setAlignment(QtCore.Qt.AlignCenter)
        self.label_info_camera_shutter.setObjectName("label_info_camera_shutter")
        self.label_info_camera_iso = QtWidgets.QLabel(self.groupBox_info_kamera)
        self.label_info_camera_iso.setEnabled(False)
        self.label_info_camera_iso.setGeometry(QtCore.QRect(15, 175, 187, 30))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(14)
        self.label_info_camera_iso.setFont(font)
        self.label_info_camera_iso.setStyleSheet("border: none;\n"
"background-color: transparent;")
        self.label_info_camera_iso.setAlignment(QtCore.Qt.AlignCenter)
        self.label_info_camera_iso.setObjectName("label_info_camera_iso")
        self.label_info_camera_fokus = QtWidgets.QLabel(self.groupBox_info_kamera)
        self.label_info_camera_fokus.setEnabled(False)
        self.label_info_camera_fokus.setGeometry(QtCore.QRect(15, 215, 187, 30))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(14)
        self.label_info_camera_fokus.setFont(font)
        self.label_info_camera_fokus.setStyleSheet("border: none;\n"
"background-color: transparent;")
        self.label_info_camera_fokus.setAlignment(QtCore.Qt.AlignCenter)
        self.label_info_camera_fokus.setObjectName("label_info_camera_fokus")
        self.label_info_camera_format = QtWidgets.QLabel(self.groupBox_info_kamera)
        self.label_info_camera_format.setEnabled(False)
        self.label_info_camera_format.setGeometry(QtCore.QRect(15, 255, 187, 30))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(14)
        self.label_info_camera_format.setFont(font)
        self.label_info_camera_format.setStyleSheet("border: none;\n"
"background-color: transparent;")
        self.label_info_camera_format.setAlignment(QtCore.Qt.AlignCenter)
        self.label_info_camera_format.setObjectName("label_info_camera_format")
        self.input_info_camera_akku = QtWidgets.QLabel(self.groupBox_info_kamera)
        self.input_info_camera_akku.setEnabled(False)
        self.input_info_camera_akku.setGeometry(QtCore.QRect(210, 55, 186, 30))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(14)
        self.input_info_camera_akku.setFont(font)
        self.input_info_camera_akku.setStyleSheet("border: none;")
        self.input_info_camera_akku.setText("")
        self.input_info_camera_akku.setAlignment(QtCore.Qt.AlignCenter)
        self.input_info_camera_akku.setObjectName("input_info_camera_akku")
        self.input_info_camera_blende = QtWidgets.QLabel(self.groupBox_info_kamera)
        self.input_info_camera_blende.setEnabled(False)
        self.input_info_camera_blende.setGeometry(QtCore.QRect(210, 95, 186, 30))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(14)
        self.input_info_camera_blende.setFont(font)
        self.input_info_camera_blende.setStyleSheet("border: none;")
        self.input_info_camera_blende.setText("")
        self.input_info_camera_blende.setAlignment(QtCore.Qt.AlignCenter)
        self.input_info_camera_blende.setObjectName("input_info_camera_blende")
        self.input_info_camera_shutter = QtWidgets.QLabel(self.groupBox_info_kamera)
        self.input_info_camera_shutter.setEnabled(False)
        self.input_info_camera_shutter.setGeometry(QtCore.QRect(210, 135, 186, 30))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(14)
        self.input_info_camera_shutter.setFont(font)
        self.input_info_camera_shutter.setStyleSheet("border: none;")
        self.input_info_camera_shutter.setText("")
        self.input_info_camera_shutter.setAlignment(QtCore.Qt.AlignCenter)
        self.input_info_camera_shutter.setObjectName("input_info_camera_shutter")
        self.input_info_camera_iso = QtWidgets.QLabel(self.groupBox_info_kamera)
        self.input_info_camera_iso.setEnabled(False)
        self.input_info_camera_iso.setGeometry(QtCore.QRect(210, 175, 186, 30))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(14)
        self.input_info_camera_iso.setFont(font)
        self.input_info_camera_iso.setStyleSheet("border: none;")
        self.input_info_camera_iso.setText("")
        self.input_info_camera_iso.setAlignment(QtCore.Qt.AlignCenter)
        self.input_info_camera_iso.setObjectName("input_info_camera_iso")
        self.input_info_camera_fokus = QtWidgets.QLabel(self.groupBox_info_kamera)
        self.input_info_camera_fokus.setEnabled(False)
        self.input_info_camera_fokus.setGeometry(QtCore.QRect(210, 215, 186, 30))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(14)
        self.input_info_camera_fokus.setFont(font)
        self.input_info_camera_fokus.setStyleSheet("")
        self.input_info_camera_fokus.setText("")
        self.input_info_camera_fokus.setAlignment(QtCore.Qt.AlignCenter)
        self.input_info_camera_fokus.setObjectName("input_info_camera_fokus")
        self.input_info_camera_format = QtWidgets.QLabel(self.groupBox_info_kamera)
        self.input_info_camera_format.setEnabled(False)
        self.input_info_camera_format.setGeometry(QtCore.QRect(210, 255, 186, 30))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(14)
        self.input_info_camera_format.setFont(font)
        self.input_info_camera_format.setStyleSheet("border: none;")
        self.input_info_camera_format.setText("")
        self.input_info_camera_format.setAlignment(QtCore.Qt.AlignCenter)
        self.input_info_camera_format.setObjectName("input_info_camera_format")
        self.groupBox_settings_kamera = QtWidgets.QGroupBox(self.groupBox_info)
        self.groupBox_settings_kamera.setEnabled(False)
        self.groupBox_settings_kamera.setGeometry(QtCore.QRect(10, 360, 400, 310))
        self.groupBox_settings_kamera.setMinimumSize(QtCore.QSize(400, 310))
        self.groupBox_settings_kamera.setMaximumSize(QtCore.QSize(400, 310))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(10)
        self.groupBox_settings_kamera.setFont(font)
        self.groupBox_settings_kamera.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_settings_kamera.setObjectName("groupBox_settings_kamera")
        self.label_settings_kamera_takes = QtWidgets.QLabel(self.groupBox_settings_kamera)
        self.label_settings_kamera_takes.setEnabled(False)
        self.label_settings_kamera_takes.setGeometry(QtCore.QRect(15, 215, 187, 30))
        self.label_settings_kamera_takes.setMinimumSize(QtCore.QSize(187, 30))
        self.label_settings_kamera_takes.setMaximumSize(QtCore.QSize(187, 30))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(14)
        self.label_settings_kamera_takes.setFont(font)
        self.label_settings_kamera_takes.setStyleSheet("")
        self.label_settings_kamera_takes.setAlignment(QtCore.Qt.AlignCenter)
        self.label_settings_kamera_takes.setObjectName("label_settings_kamera_takes")
        self.lineEdit_settings_kamera_takes = QtWidgets.QLineEdit(self.groupBox_settings_kamera)
        self.lineEdit_settings_kamera_takes.setEnabled(False)
        self.lineEdit_settings_kamera_takes.setGeometry(QtCore.QRect(210, 215, 180, 30))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(14)
        self.lineEdit_settings_kamera_takes.setFont(font)
        self.lineEdit_settings_kamera_takes.setStyleSheet("")
        self.lineEdit_settings_kamera_takes.setText("")
        self.lineEdit_settings_kamera_takes.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_settings_kamera_takes.setObjectName("lineEdit_settings_kamera_takes")
        self.pushButton_settings_kamera = QtWidgets.QPushButton(self.groupBox_settings_kamera)
        self.pushButton_settings_kamera.setEnabled(False)
        self.pushButton_settings_kamera.setGeometry(QtCore.QRect(125, 150, 150, 35))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(14)
        self.pushButton_settings_kamera.setFont(font)
        self.pushButton_settings_kamera.setStyleSheet("")
        self.pushButton_settings_kamera.setFlat(False)
        self.pushButton_settings_kamera.setObjectName("pushButton_settings_kamera")
        self.label_settings_kamera_blende = QtWidgets.QLabel(self.groupBox_settings_kamera)
        self.label_settings_kamera_blende.setEnabled(False)
        self.label_settings_kamera_blende.setGeometry(QtCore.QRect(15, 30, 187, 30))
        self.label_settings_kamera_blende.setMinimumSize(QtCore.QSize(187, 30))
        self.label_settings_kamera_blende.setMaximumSize(QtCore.QSize(187, 30))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(14)
        self.label_settings_kamera_blende.setFont(font)
        self.label_settings_kamera_blende.setStyleSheet("")
        self.label_settings_kamera_blende.setAlignment(QtCore.Qt.AlignCenter)
        self.label_settings_kamera_blende.setObjectName("label_settings_kamera_blende")
        self.label_settings_kamera_shutter = QtWidgets.QLabel(self.groupBox_settings_kamera)
        self.label_settings_kamera_shutter.setEnabled(False)
        self.label_settings_kamera_shutter.setGeometry(QtCore.QRect(15, 70, 187, 30))
        self.label_settings_kamera_shutter.setMinimumSize(QtCore.QSize(187, 30))
        self.label_settings_kamera_shutter.setMaximumSize(QtCore.QSize(187, 30))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(14)
        self.label_settings_kamera_shutter.setFont(font)
        self.label_settings_kamera_shutter.setStyleSheet("")
        self.label_settings_kamera_shutter.setAlignment(QtCore.Qt.AlignCenter)
        self.label_settings_kamera_shutter.setObjectName("label_settings_kamera_shutter")
        self.label_settings_kamera_iso = QtWidgets.QLabel(self.groupBox_settings_kamera)
        self.label_settings_kamera_iso.setEnabled(False)
        self.label_settings_kamera_iso.setGeometry(QtCore.QRect(15, 110, 187, 30))
        self.label_settings_kamera_iso.setMinimumSize(QtCore.QSize(187, 30))
        self.label_settings_kamera_iso.setMaximumSize(QtCore.QSize(187, 30))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(14)
        self.label_settings_kamera_iso.setFont(font)
        self.label_settings_kamera_iso.setStyleSheet("")
        self.label_settings_kamera_iso.setAlignment(QtCore.Qt.AlignCenter)
        self.label_settings_kamera_iso.setObjectName("label_settings_kamera_iso")
        self.comboBox_settings_kamera_blende = QtWidgets.QComboBox(self.groupBox_settings_kamera)
        self.comboBox_settings_kamera_blende.setGeometry(QtCore.QRect(210, 30, 180, 30))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(14)
        self.comboBox_settings_kamera_blende.setFont(font)
        self.comboBox_settings_kamera_blende.setCurrentText("")
        self.comboBox_settings_kamera_blende.setObjectName("comboBox_settings_kamera_blende")
        self.comboBox_settings_kamera_shutter = QtWidgets.QComboBox(self.groupBox_settings_kamera)
        self.comboBox_settings_kamera_shutter.setGeometry(QtCore.QRect(210, 70, 180, 30))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(14)
        self.comboBox_settings_kamera_shutter.setFont(font)
        self.comboBox_settings_kamera_shutter.setCurrentText("")
        self.comboBox_settings_kamera_shutter.setObjectName("comboBox_settings_kamera_shutter")
        self.comboBox_settings_kamera_iso = QtWidgets.QComboBox(self.groupBox_settings_kamera)
        self.comboBox_settings_kamera_iso.setGeometry(QtCore.QRect(210, 110, 180, 30))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(14)
        self.comboBox_settings_kamera_iso.setFont(font)
        self.comboBox_settings_kamera_iso.setCurrentText("")
        self.comboBox_settings_kamera_iso.setObjectName("comboBox_settings_kamera_iso")
        self.pushButton_settings_kamera_takes = QtWidgets.QPushButton(self.groupBox_settings_kamera)
        self.pushButton_settings_kamera_takes.setEnabled(False)
        self.pushButton_settings_kamera_takes.setGeometry(QtCore.QRect(125, 260, 150, 35))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(14)
        self.pushButton_settings_kamera_takes.setFont(font)
        self.pushButton_settings_kamera_takes.setStyleSheet("")
        self.pushButton_settings_kamera_takes.setFlat(False)
        self.pushButton_settings_kamera_takes.setObjectName("pushButton_settings_kamera_takes")
        self.line_3 = QtWidgets.QFrame(self.groupBox_settings_kamera)
        self.line_3.setGeometry(QtCore.QRect(20, 200, 360, 1))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout_left.addWidget(self.groupBox_info)
        self.horizontalLayout.addLayout(self.verticalLayout_left)
        self.verticalLayout_center = QtWidgets.QVBoxLayout()
        self.verticalLayout_center.setObjectName("verticalLayout_center")
        self.groupBox_settings = QtWidgets.QGroupBox(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_settings.setFont(font)
        self.groupBox_settings.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_settings.setObjectName("groupBox_settings")
        self.groupBox_settings_slider = QtWidgets.QGroupBox(self.groupBox_settings)
        self.groupBox_settings_slider.setEnabled(False)
        self.groupBox_settings_slider.setGeometry(QtCore.QRect(10, 360, 400, 310))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(10)
        self.groupBox_settings_slider.setFont(font)
        self.groupBox_settings_slider.setStyleSheet("")
        self.groupBox_settings_slider.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_settings_slider.setObjectName("groupBox_settings_slider")
        self.label_settings_slider_start = QtWidgets.QLabel(self.groupBox_settings_slider)
        self.label_settings_slider_start.setGeometry(QtCore.QRect(15, 215, 187, 30))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(14)
        self.label_settings_slider_start.setFont(font)
        self.label_settings_slider_start.setStyleSheet("border: none;\n"
"background-color: transparent;")
        self.label_settings_slider_start.setAlignment(QtCore.Qt.AlignCenter)
        self.label_settings_slider_start.setObjectName("label_settings_slider_start")
        self.comboBox_settings_slider_start = QtWidgets.QComboBox(self.groupBox_settings_slider)
        self.comboBox_settings_slider_start.setGeometry(QtCore.QRect(210, 215, 180, 30))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(14)
        self.comboBox_settings_slider_start.setFont(font)
        self.comboBox_settings_slider_start.setStyleSheet("")
        self.comboBox_settings_slider_start.setEditable(False)
        self.comboBox_settings_slider_start.setObjectName("comboBox_settings_slider_start")
        self.comboBox_settings_slider_start.addItem("")
        self.comboBox_settings_slider_start.addItem("")
        self.comboBox_settings_slider_start.addItem("")
        self.label_settings_slider_richtung = QtWidgets.QLabel(self.groupBox_settings_slider)
        self.label_settings_slider_richtung.setGeometry(QtCore.QRect(15, 30, 187, 30))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(14)
        self.label_settings_slider_richtung.setFont(font)
        self.label_settings_slider_richtung.setStyleSheet("border: none;\n"
"background-color: transparent;")
        self.label_settings_slider_richtung.setAlignment(QtCore.Qt.AlignCenter)
        self.label_settings_slider_richtung.setObjectName("label_settings_slider_richtung")
        self.comboBox_settings_slider_richtung = QtWidgets.QComboBox(self.groupBox_settings_slider)
        self.comboBox_settings_slider_richtung.setGeometry(QtCore.QRect(210, 30, 180, 30))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(14)
        self.comboBox_settings_slider_richtung.setFont(font)
        self.comboBox_settings_slider_richtung.setStyleSheet("")
        self.comboBox_settings_slider_richtung.setEditable(False)
        self.comboBox_settings_slider_richtung.setObjectName("comboBox_settings_slider_richtung")
        self.comboBox_settings_slider_richtung.addItem("")
        self.comboBox_settings_slider_richtung.addItem("")
        self.label_settings_slider_steps = QtWidgets.QLabel(self.groupBox_settings_slider)
        self.label_settings_slider_steps.setGeometry(QtCore.QRect(15, 70, 187, 30))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(14)
        self.label_settings_slider_steps.setFont(font)
        self.label_settings_slider_steps.setStyleSheet("")
        self.label_settings_slider_steps.setAlignment(QtCore.Qt.AlignCenter)
        self.label_settings_slider_steps.setObjectName("label_settings_slider_steps")
        self.lineEdit_settings_slider_steps = QtWidgets.QLineEdit(self.groupBox_settings_slider)
        self.lineEdit_settings_slider_steps.setEnabled(False)
        self.lineEdit_settings_slider_steps.setGeometry(QtCore.QRect(210, 70, 180, 30))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(14)
        self.lineEdit_settings_slider_steps.setFont(font)
        self.lineEdit_settings_slider_steps.setStyleSheet("")
        self.lineEdit_settings_slider_steps.setText("")
        self.lineEdit_settings_slider_steps.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_settings_slider_steps.setObjectName("lineEdit_settings_slider_steps")
        self.label_settings_slider_frequenz = QtWidgets.QLabel(self.groupBox_settings_slider)
        self.label_settings_slider_frequenz.setGeometry(QtCore.QRect(15, 110, 187, 30))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(14)
        self.label_settings_slider_frequenz.setFont(font)
        self.label_settings_slider_frequenz.setStyleSheet("border: none;\n"
"background-color: transparent;")
        self.label_settings_slider_frequenz.setAlignment(QtCore.Qt.AlignCenter)
        self.label_settings_slider_frequenz.setObjectName("label_settings_slider_frequenz")
        self.lineEdit_settings_slider_frequenz = QtWidgets.QLineEdit(self.groupBox_settings_slider)
        self.lineEdit_settings_slider_frequenz.setEnabled(False)
        self.lineEdit_settings_slider_frequenz.setGeometry(QtCore.QRect(210, 110, 180, 30))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(14)
        self.lineEdit_settings_slider_frequenz.setFont(font)
        self.lineEdit_settings_slider_frequenz.setStyleSheet("")
        self.lineEdit_settings_slider_frequenz.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_settings_slider_frequenz.setObjectName("lineEdit_settings_slider_frequenz")
        self.pushButton_settings_slider = QtWidgets.QPushButton(self.groupBox_settings_slider)
        self.pushButton_settings_slider.setEnabled(False)
        self.pushButton_settings_slider.setGeometry(QtCore.QRect(125, 150, 150, 35))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(14)
        self.pushButton_settings_slider.setFont(font)
        self.pushButton_settings_slider.setStyleSheet("")
        self.pushButton_settings_slider.setFlat(False)
        self.pushButton_settings_slider.setObjectName("pushButton_settings_slider")
        self.line_2 = QtWidgets.QFrame(self.groupBox_settings_slider)
        self.line_2.setGeometry(QtCore.QRect(20, 200, 360, 1))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.pushButton_steuerung_slider_position = QtWidgets.QPushButton(self.groupBox_settings_slider)
        self.pushButton_steuerung_slider_position.setEnabled(False)
        self.pushButton_steuerung_slider_position.setGeometry(QtCore.QRect(125, 260, 150, 35))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(14)
        self.pushButton_steuerung_slider_position.setFont(font)
        self.pushButton_steuerung_slider_position.setFlat(False)
        self.pushButton_steuerung_slider_position.setObjectName("pushButton_steuerung_slider_position")
        self.groupBox_info_slider = QtWidgets.QGroupBox(self.groupBox_settings)
        self.groupBox_info_slider.setEnabled(False)
        self.groupBox_info_slider.setGeometry(QtCore.QRect(10, 30, 400, 250))
        self.groupBox_info_slider.setMinimumSize(QtCore.QSize(400, 250))
        self.groupBox_info_slider.setMaximumSize(QtCore.QSize(400, 250))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(10)
        self.groupBox_info_slider.setFont(font)
        self.groupBox_info_slider.setStyleSheet("")
        self.groupBox_info_slider.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_info_slider.setObjectName("groupBox_info_slider")
        self.label_info_slider_links = QtWidgets.QLabel(self.groupBox_info_slider)
        self.label_info_slider_links.setEnabled(False)
        self.label_info_slider_links.setGeometry(QtCore.QRect(15, 15, 187, 30))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(14)
        self.label_info_slider_links.setFont(font)
        self.label_info_slider_links.setStyleSheet("border: none;\n"
"background-color: transparent;")
        self.label_info_slider_links.setAlignment(QtCore.Qt.AlignCenter)
        self.label_info_slider_links.setObjectName("label_info_slider_links")
        self.label_info_slider_rechts = QtWidgets.QLabel(self.groupBox_info_slider)
        self.label_info_slider_rechts.setEnabled(False)
        self.label_info_slider_rechts.setGeometry(QtCore.QRect(15, 55, 187, 30))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(14)
        self.label_info_slider_rechts.setFont(font)
        self.label_info_slider_rechts.setStyleSheet("border: none;\n"
"background-color: transparent;")
        self.label_info_slider_rechts.setAlignment(QtCore.Qt.AlignCenter)
        self.label_info_slider_rechts.setObjectName("label_info_slider_rechts")
        self.input_info_slider_links = QtWidgets.QLabel(self.groupBox_info_slider)
        self.input_info_slider_links.setEnabled(False)
        self.input_info_slider_links.setGeometry(QtCore.QRect(210, 15, 186, 30))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(14)
        self.input_info_slider_links.setFont(font)
        self.input_info_slider_links.setStyleSheet("")
        self.input_info_slider_links.setText("")
        self.input_info_slider_links.setAlignment(QtCore.Qt.AlignCenter)
        self.input_info_slider_links.setObjectName("input_info_slider_links")
        self.input_info_slider_rechts = QtWidgets.QLabel(self.groupBox_info_slider)
        self.input_info_slider_rechts.setEnabled(False)
        self.input_info_slider_rechts.setGeometry(QtCore.QRect(210, 55, 186, 30))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(14)
        self.input_info_slider_rechts.setFont(font)
        self.input_info_slider_rechts.setStyleSheet("border: none;")
        self.input_info_slider_rechts.setText("")
        self.input_info_slider_rechts.setAlignment(QtCore.Qt.AlignCenter)
        self.input_info_slider_rechts.setObjectName("input_info_slider_rechts")
        self.label_info_slider_frequenz = QtWidgets.QLabel(self.groupBox_info_slider)
        self.label_info_slider_frequenz.setEnabled(False)
        self.label_info_slider_frequenz.setGeometry(QtCore.QRect(15, 135, 187, 30))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(14)
        self.label_info_slider_frequenz.setFont(font)
        self.label_info_slider_frequenz.setStyleSheet("border: none;\n"
"background-color: transparent;")
        self.label_info_slider_frequenz.setAlignment(QtCore.Qt.AlignCenter)
        self.label_info_slider_frequenz.setObjectName("label_info_slider_frequenz")
        self.input_info_slider_status = QtWidgets.QLabel(self.groupBox_info_slider)
        self.input_info_slider_status.setEnabled(False)
        self.input_info_slider_status.setGeometry(QtCore.QRect(210, 95, 186, 30))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(14)
        self.input_info_slider_status.setFont(font)
        self.input_info_slider_status.setStyleSheet("border: none;")
        self.input_info_slider_status.setText("")
        self.input_info_slider_status.setAlignment(QtCore.Qt.AlignCenter)
        self.input_info_slider_status.setObjectName("input_info_slider_status")
        self.label_info_slider_status = QtWidgets.QLabel(self.groupBox_info_slider)
        self.label_info_slider_status.setEnabled(False)
        self.label_info_slider_status.setGeometry(QtCore.QRect(15, 95, 187, 30))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(14)
        self.label_info_slider_status.setFont(font)
        self.label_info_slider_status.setStyleSheet("border: none;\n"
"background-color: transparent;")
        self.label_info_slider_status.setAlignment(QtCore.Qt.AlignCenter)
        self.label_info_slider_status.setObjectName("label_info_slider_status")
        self.input_info_slider_frequenz = QtWidgets.QLabel(self.groupBox_info_slider)
        self.input_info_slider_frequenz.setEnabled(False)
        self.input_info_slider_frequenz.setGeometry(QtCore.QRect(210, 135, 186, 30))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(14)
        self.input_info_slider_frequenz.setFont(font)
        self.input_info_slider_frequenz.setStyleSheet("border: none;")
        self.input_info_slider_frequenz.setText("")
        self.input_info_slider_frequenz.setAlignment(QtCore.Qt.AlignCenter)
        self.input_info_slider_frequenz.setObjectName("input_info_slider_frequenz")
        self.label_info_slider_richtung = QtWidgets.QLabel(self.groupBox_info_slider)
        self.label_info_slider_richtung.setEnabled(False)
        self.label_info_slider_richtung.setGeometry(QtCore.QRect(15, 175, 187, 30))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(14)
        self.label_info_slider_richtung.setFont(font)
        self.label_info_slider_richtung.setStyleSheet("border: none;\n"
"background-color: transparent;")
        self.label_info_slider_richtung.setAlignment(QtCore.Qt.AlignCenter)
        self.label_info_slider_richtung.setObjectName("label_info_slider_richtung")
        self.input_info_slider_richtung = QtWidgets.QLabel(self.groupBox_info_slider)
        self.input_info_slider_richtung.setEnabled(False)
        self.input_info_slider_richtung.setGeometry(QtCore.QRect(210, 175, 186, 30))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(14)
        self.input_info_slider_richtung.setFont(font)
        self.input_info_slider_richtung.setStyleSheet("border: none;")
        self.input_info_slider_richtung.setText("")
        self.input_info_slider_richtung.setAlignment(QtCore.Qt.AlignCenter)
        self.input_info_slider_richtung.setObjectName("input_info_slider_richtung")
        self.label_info_slider_steps = QtWidgets.QLabel(self.groupBox_info_slider)
        self.label_info_slider_steps.setEnabled(False)
        self.label_info_slider_steps.setGeometry(QtCore.QRect(15, 210, 187, 30))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(14)
        self.label_info_slider_steps.setFont(font)
        self.label_info_slider_steps.setStyleSheet("border: none;\n"
"background-color: transparent;")
        self.label_info_slider_steps.setAlignment(QtCore.Qt.AlignCenter)
        self.label_info_slider_steps.setObjectName("label_info_slider_steps")
        self.input_info_slider_steps = QtWidgets.QLabel(self.groupBox_info_slider)
        self.input_info_slider_steps.setEnabled(False)
        self.input_info_slider_steps.setGeometry(QtCore.QRect(210, 210, 186, 30))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(14)
        self.input_info_slider_steps.setFont(font)
        self.input_info_slider_steps.setStyleSheet("border: none;")
        self.input_info_slider_steps.setText("")
        self.input_info_slider_steps.setAlignment(QtCore.Qt.AlignCenter)
        self.input_info_slider_steps.setObjectName("input_info_slider_steps")
        self.verticalLayout_center.addWidget(self.groupBox_settings)
        self.horizontalLayout.addLayout(self.verticalLayout_center)
        self.verticalLayout_right = QtWidgets.QVBoxLayout()
        self.verticalLayout_right.setSpacing(15)
        self.verticalLayout_right.setObjectName("verticalLayout_right")
        self.groupBox_info_server = QtWidgets.QGroupBox(self.horizontalLayoutWidget)
        self.groupBox_info_server.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_info_server.sizePolicy().hasHeightForWidth())
        self.groupBox_info_server.setSizePolicy(sizePolicy)
        self.groupBox_info_server.setMinimumSize(QtCore.QSize(420, 120))
        self.groupBox_info_server.setMaximumSize(QtCore.QSize(420, 120))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_info_server.setFont(font)
        self.groupBox_info_server.setStyleSheet("")
        self.groupBox_info_server.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_info_server.setObjectName("groupBox_info_server")
        self.groupBox = QtWidgets.QGroupBox(self.groupBox_info_server)
        self.groupBox.setGeometry(QtCore.QRect(10, 30, 400, 60))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(10)
        self.groupBox.setFont(font)
        self.groupBox.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox.setObjectName("groupBox")
        self.label_info_server_ip = QtWidgets.QLabel(self.groupBox)
        self.label_info_server_ip.setEnabled(False)
        self.label_info_server_ip.setGeometry(QtCore.QRect(210, 15, 187, 30))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(14)
        self.label_info_server_ip.setFont(font)
        self.label_info_server_ip.setStyleSheet("")
        self.label_info_server_ip.setAlignment(QtCore.Qt.AlignCenter)
        self.label_info_server_ip.setObjectName("label_info_server_ip")
        self.label_info_server = QtWidgets.QLabel(self.groupBox)
        self.label_info_server.setEnabled(False)
        self.label_info_server.setGeometry(QtCore.QRect(15, 15, 187, 30))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(14)
        self.label_info_server.setFont(font)
        self.label_info_server.setStyleSheet("")
        self.label_info_server.setAlignment(QtCore.Qt.AlignCenter)
        self.label_info_server.setObjectName("label_info_server")
        self.verticalLayout_right.addWidget(self.groupBox_info_server)
        self.groupBox_steuerung = QtWidgets.QGroupBox(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_steuerung.setFont(font)
        self.groupBox_steuerung.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_steuerung.setObjectName("groupBox_steuerung")
        self.groupBox_steuerung_kamera = QtWidgets.QGroupBox(self.groupBox_steuerung)
        self.groupBox_steuerung_kamera.setEnabled(False)
        self.groupBox_steuerung_kamera.setGeometry(QtCore.QRect(10, 30, 400, 90))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(10)
        self.groupBox_steuerung_kamera.setFont(font)
        self.groupBox_steuerung_kamera.setStyleSheet("")
        self.groupBox_steuerung_kamera.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_steuerung_kamera.setObjectName("groupBox_steuerung_kamera")
        self.pushButton_steuerung_kamera = QtWidgets.QPushButton(self.groupBox_steuerung_kamera)
        self.pushButton_steuerung_kamera.setEnabled(False)
        self.pushButton_steuerung_kamera.setGeometry(QtCore.QRect(125, 30, 150, 35))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(14)
        self.pushButton_steuerung_kamera.setFont(font)
        self.pushButton_steuerung_kamera.setFlat(False)
        self.pushButton_steuerung_kamera.setObjectName("pushButton_steuerung_kamera")
        self.groupBox_steuerung_slider = QtWidgets.QGroupBox(self.groupBox_steuerung)
        self.groupBox_steuerung_slider.setEnabled(False)
        self.groupBox_steuerung_slider.setGeometry(QtCore.QRect(10, 135, 400, 90))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(10)
        self.groupBox_steuerung_slider.setFont(font)
        self.groupBox_steuerung_slider.setStyleSheet("")
        self.groupBox_steuerung_slider.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_steuerung_slider.setObjectName("groupBox_steuerung_slider")
        self.pushButton_steuerung_slider = QtWidgets.QPushButton(self.groupBox_steuerung_slider)
        self.pushButton_steuerung_slider.setEnabled(False)
        self.pushButton_steuerung_slider.setGeometry(QtCore.QRect(125, 30, 150, 35))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(14)
        self.pushButton_steuerung_slider.setFont(font)
        self.pushButton_steuerung_slider.setFlat(False)
        self.pushButton_steuerung_slider.setObjectName("pushButton_steuerung_slider")
        self.groupBox_steuerung_abstand = QtWidgets.QGroupBox(self.groupBox_steuerung)
        self.groupBox_steuerung_abstand.setEnabled(False)
        self.groupBox_steuerung_abstand.setGeometry(QtCore.QRect(10, 240, 400, 90))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(10)
        self.groupBox_steuerung_abstand.setFont(font)
        self.groupBox_steuerung_abstand.setStyleSheet("")
        self.groupBox_steuerung_abstand.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_steuerung_abstand.setObjectName("groupBox_steuerung_abstand")
        self.pushButton_steuerung_abstand = QtWidgets.QPushButton(self.groupBox_steuerung_abstand)
        self.pushButton_steuerung_abstand.setEnabled(False)
        self.pushButton_steuerung_abstand.setGeometry(QtCore.QRect(125, 30, 150, 35))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(14)
        self.pushButton_steuerung_abstand.setFont(font)
        self.pushButton_steuerung_abstand.setFlat(False)
        self.pushButton_steuerung_abstand.setObjectName("pushButton_steuerung_abstand")
        self.groupBox_steuerung_manuell = QtWidgets.QGroupBox(self.groupBox_steuerung)
        self.groupBox_steuerung_manuell.setEnabled(False)
        self.groupBox_steuerung_manuell.setGeometry(QtCore.QRect(10, 345, 400, 190))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(10)
        self.groupBox_steuerung_manuell.setFont(font)
        self.groupBox_steuerung_manuell.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_steuerung_manuell.setObjectName("groupBox_steuerung_manuell")
        self.pushButton_steuerung_manuell = QtWidgets.QPushButton(self.groupBox_steuerung_manuell)
        self.pushButton_steuerung_manuell.setEnabled(False)
        self.pushButton_steuerung_manuell.setGeometry(QtCore.QRect(125, 140, 150, 35))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(14)
        self.pushButton_steuerung_manuell.setFont(font)
        self.pushButton_steuerung_manuell.setObjectName("pushButton_steuerung_manuell")
        self.label_steuerung_manuell_richtung = QtWidgets.QLabel(self.groupBox_steuerung_manuell)
        self.label_steuerung_manuell_richtung.setGeometry(QtCore.QRect(15, 30, 187, 30))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(14)
        self.label_steuerung_manuell_richtung.setFont(font)
        self.label_steuerung_manuell_richtung.setAlignment(QtCore.Qt.AlignCenter)
        self.label_steuerung_manuell_richtung.setObjectName("label_steuerung_manuell_richtung")
        self.comboBox_steuerung_manuell_richtung = QtWidgets.QComboBox(self.groupBox_steuerung_manuell)
        self.comboBox_steuerung_manuell_richtung.setGeometry(QtCore.QRect(210, 30, 180, 30))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(14)
        self.comboBox_steuerung_manuell_richtung.setFont(font)
        self.comboBox_steuerung_manuell_richtung.setObjectName("comboBox_steuerung_manuell_richtung")
        self.comboBox_steuerung_manuell_richtung.addItem("")
        self.comboBox_steuerung_manuell_richtung.addItem("")
        self.label_steuerung_manuell_distanz = QtWidgets.QLabel(self.groupBox_steuerung_manuell)
        self.label_steuerung_manuell_distanz.setGeometry(QtCore.QRect(15, 70, 187, 30))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(14)
        self.label_steuerung_manuell_distanz.setFont(font)
        self.label_steuerung_manuell_distanz.setAlignment(QtCore.Qt.AlignCenter)
        self.label_steuerung_manuell_distanz.setObjectName("label_steuerung_manuell_distanz")
        self.lineEdit_steuerung_manuell_distanz = QtWidgets.QLineEdit(self.groupBox_steuerung_manuell)
        self.lineEdit_steuerung_manuell_distanz.setGeometry(QtCore.QRect(210, 70, 180, 30))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(14)
        self.lineEdit_steuerung_manuell_distanz.setFont(font)
        self.lineEdit_steuerung_manuell_distanz.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_steuerung_manuell_distanz.setObjectName("lineEdit_steuerung_manuell_distanz")
        self.label_steuerung_manuell_info = QtWidgets.QLabel(self.groupBox_steuerung_manuell)
        self.label_steuerung_manuell_info.setGeometry(QtCore.QRect(20, 110, 360, 15))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(10)
        self.label_steuerung_manuell_info.setFont(font)
        self.label_steuerung_manuell_info.setAlignment(QtCore.Qt.AlignCenter)
        self.label_steuerung_manuell_info.setObjectName("label_steuerung_manuell_info")
        self.verticalLayout_right.addWidget(self.groupBox_steuerung)
        self.horizontalLayout.addLayout(self.verticalLayout_right)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1280, 21))
        self.menubar.setObjectName("menubar")
        self.menuProgramm = QtWidgets.QMenu(self.menubar)
        self.menuProgramm.setObjectName("menuProgramm")
        self.menuServer = QtWidgets.QMenu(self.menubar)
        self.menuServer.setObjectName("menuServer")
        MainWindow.setMenuBar(self.menubar)
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionClose = QtWidgets.QAction(MainWindow)
        self.actionClose.setObjectName("actionClose")
        self.actionConnect = QtWidgets.QAction(MainWindow)
        self.actionConnect.setObjectName("actionConnect")
        self.actionDisconnect = QtWidgets.QAction(MainWindow)
        self.actionDisconnect.setEnabled(False)
        self.actionDisconnect.setObjectName("actionDisconnect")
        self.actionConnectCamera = QtWidgets.QAction(MainWindow)
        self.actionConnectCamera.setEnabled(False)
        self.actionConnectCamera.setObjectName("actionConnectCamera")
        self.actionDisconnectCamera = QtWidgets.QAction(MainWindow)
        self.actionDisconnectCamera.setEnabled(False)
        self.actionDisconnectCamera.setObjectName("actionDisconnectCamera")
        self.actionSensoren_verbinden = QtWidgets.QAction(MainWindow)
        self.actionSensoren_verbinden.setObjectName("actionSensoren_verbinden")
        self.actionSensoren_Verbindung_trennen = QtWidgets.QAction(MainWindow)
        self.actionSensoren_Verbindung_trennen.setObjectName("actionSensoren_Verbindung_trennen")
        self.actionConnectMotor = QtWidgets.QAction(MainWindow)
        self.actionConnectMotor.setEnabled(False)
        self.actionConnectMotor.setObjectName("actionConnectMotor")
        self.actionDisconnectMotor = QtWidgets.QAction(MainWindow)
        self.actionDisconnectMotor.setEnabled(False)
        self.actionDisconnectMotor.setObjectName("actionDisconnectMotor")
        self.actionConnectSensors = QtWidgets.QAction(MainWindow)
        self.actionConnectSensors.setEnabled(False)
        self.actionConnectSensors.setObjectName("actionConnectSensors")
        self.actionDisconnectSensors = QtWidgets.QAction(MainWindow)
        self.actionDisconnectSensors.setEnabled(False)
        self.actionDisconnectSensors.setObjectName("actionDisconnectSensors")
        self.menuProgramm.addAction(self.actionAbout)
        self.menuProgramm.addAction(self.actionClose)
        self.menuServer.addAction(self.actionConnect)
        self.menuServer.addAction(self.actionDisconnect)
        self.menuServer.addSeparator()
        self.menuServer.addAction(self.actionConnectCamera)
        self.menuServer.addAction(self.actionDisconnectCamera)
        self.menuServer.addSeparator()
        self.menuServer.addAction(self.actionConnectMotor)
        self.menuServer.addAction(self.actionDisconnectMotor)
        self.menuServer.addSeparator()
        self.menuServer.addAction(self.actionConnectSensors)
        self.menuServer.addAction(self.actionDisconnectSensors)
        self.menubar.addAction(self.menuProgramm.menuAction())
        self.menubar.addAction(self.menuServer.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox_info.setTitle(_translate("MainWindow", "Kamera"))
        self.groupBox_info_kamera.setTitle(_translate("MainWindow", "Informationen"))
        self.label_info_camera_name.setText(_translate("MainWindow", "Verbunden mit:"))
        self.input_info_camera_name.setText(_translate("MainWindow", "Nicht verbunden"))
        self.label_info_camera_akku.setText(_translate("MainWindow", "Akku:"))
        self.label_info_camera_blende.setText(_translate("MainWindow", "Blende:"))
        self.label_info_camera_shutter.setText(_translate("MainWindow", "Verschlusszeit:"))
        self.label_info_camera_iso.setText(_translate("MainWindow", "ISO:"))
        self.label_info_camera_fokus.setText(_translate("MainWindow", "Fokus:"))
        self.label_info_camera_format.setText(_translate("MainWindow", "Bildformat:"))
        self.groupBox_settings_kamera.setTitle(_translate("MainWindow", "Einstellungen"))
        self.label_settings_kamera_takes.setText(_translate("MainWindow", "Aufnahmen:"))
        self.lineEdit_settings_kamera_takes.setPlaceholderText(_translate("MainWindow", "Aufnahmen"))
        self.pushButton_settings_kamera.setText(_translate("MainWindow", "Einstellen"))
        self.label_settings_kamera_blende.setText(_translate("MainWindow", "Blende:"))
        self.label_settings_kamera_shutter.setText(_translate("MainWindow", "Verschlusszeit:"))
        self.label_settings_kamera_iso.setText(_translate("MainWindow", "ISO:"))
        self.pushButton_settings_kamera_takes.setText(_translate("MainWindow", "Einstellen"))
        self.groupBox_settings.setTitle(_translate("MainWindow", "Slider"))
        self.groupBox_settings_slider.setTitle(_translate("MainWindow", "Einstellungen"))
        self.label_settings_slider_start.setText(_translate("MainWindow", "Startpunkt:"))
        self.comboBox_settings_slider_start.setItemText(0, _translate("MainWindow", "Links"))
        self.comboBox_settings_slider_start.setItemText(1, _translate("MainWindow", "Mitte"))
        self.comboBox_settings_slider_start.setItemText(2, _translate("MainWindow", "Rechts"))
        self.label_settings_slider_richtung.setText(_translate("MainWindow", "Richtung:"))
        self.comboBox_settings_slider_richtung.setItemText(0, _translate("MainWindow", "Rechts"))
        self.comboBox_settings_slider_richtung.setItemText(1, _translate("MainWindow", "Links"))
        self.label_settings_slider_steps.setText(_translate("MainWindow", "Distanz:"))
        self.lineEdit_settings_slider_steps.setPlaceholderText(_translate("MainWindow", "Strecke in cm"))
        self.label_settings_slider_frequenz.setText(_translate("MainWindow", "Frequenz:"))
        self.lineEdit_settings_slider_frequenz.setPlaceholderText(_translate("MainWindow", "Schritte/Sekunde"))
        self.pushButton_settings_slider.setText(_translate("MainWindow", "Einstellen"))
        self.pushButton_steuerung_slider_position.setText(_translate("MainWindow", "Positionieren"))
        self.groupBox_info_slider.setTitle(_translate("MainWindow", "Informationen"))
        self.label_info_slider_links.setText(_translate("MainWindow", "Abstand Links:"))
        self.label_info_slider_rechts.setText(_translate("MainWindow", "Abstand Rechts:"))
        self.label_info_slider_frequenz.setText(_translate("MainWindow", "Frequenz:"))
        self.label_info_slider_status.setText(_translate("MainWindow", "Status:"))
        self.label_info_slider_richtung.setText(_translate("MainWindow", "Richtung:"))
        self.label_info_slider_steps.setText(_translate("MainWindow", "Distanz:"))
        self.groupBox_info_server.setTitle(_translate("MainWindow", "Server"))
        self.groupBox.setTitle(_translate("MainWindow", "Informationen"))
        self.label_info_server_ip.setText(_translate("MainWindow", "Nicht verbunden"))
        self.label_info_server.setText(_translate("MainWindow", "Verbunden mit:"))
        self.groupBox_steuerung.setTitle(_translate("MainWindow", "Steuerung"))
        self.groupBox_steuerung_kamera.setTitle(_translate("MainWindow", "Kamera"))
        self.pushButton_steuerung_kamera.setText(_translate("MainWindow", "Auslösen"))
        self.groupBox_steuerung_slider.setTitle(_translate("MainWindow", "Slider"))
        self.pushButton_steuerung_slider.setText(_translate("MainWindow", "Starten"))
        self.groupBox_steuerung_abstand.setTitle(_translate("MainWindow", "Abstand"))
        self.pushButton_steuerung_abstand.setText(_translate("MainWindow", "Neu Messen"))
        self.groupBox_steuerung_manuell.setTitle(_translate("MainWindow", "Manuell"))
        self.pushButton_steuerung_manuell.setText(_translate("MainWindow", "Bewegen"))
        self.label_steuerung_manuell_richtung.setText(_translate("MainWindow", "Richtung:"))
        self.comboBox_steuerung_manuell_richtung.setItemText(0, _translate("MainWindow", "Rechts"))
        self.comboBox_steuerung_manuell_richtung.setItemText(1, _translate("MainWindow", "Links"))
        self.label_steuerung_manuell_distanz.setText(_translate("MainWindow", "Distanz:"))
        self.lineEdit_steuerung_manuell_distanz.setPlaceholderText(_translate("MainWindow", "Schritte"))
        self.label_steuerung_manuell_info.setText(_translate("MainWindow", "1 Schritt = 0,2mm. 1 Umdrehung = 200 Schritte = 4cm"))
        self.menuProgramm.setTitle(_translate("MainWindow", "Programm"))
        self.menuServer.setTitle(_translate("MainWindow", "Server"))
        self.actionAbout.setText(_translate("MainWindow", "Über"))
        self.actionAbout.setShortcut(_translate("MainWindow", "Ctrl+A"))
        self.actionClose.setText(_translate("MainWindow", "Beenden"))
        self.actionClose.setShortcut(_translate("MainWindow", "Ctrl+X"))
        self.actionConnect.setText(_translate("MainWindow", "Verbinden"))
        self.actionDisconnect.setText(_translate("MainWindow", "Verbindung Trennen"))
        self.actionConnectCamera.setText(_translate("MainWindow", "Kamera verbinden"))
        self.actionDisconnectCamera.setText(_translate("MainWindow", "Kamera Verbindung trennen"))
        self.actionSensoren_verbinden.setText(_translate("MainWindow", "Sensoren verbinden"))
        self.actionSensoren_Verbindung_trennen.setText(_translate("MainWindow", "Sensoren Verbindung trennen"))
        self.actionConnectMotor.setText(_translate("MainWindow", "Motor verbinden"))
        self.actionDisconnectMotor.setText(_translate("MainWindow", "Motor Verbindung trennen"))
        self.actionConnectSensors.setText(_translate("MainWindow", "Sensoren verbinden"))
        self.actionDisconnectSensors.setText(_translate("MainWindow", "Sensoren Verbindung trennen"))
